### ISSUE TITLE
Are the plugin hooks documented?

### ISSUE THREAD

**Issue by LordPachelbel** [mailpoet/mailpoet#1750]
We installed https://wordpress.org/plugins/subtitles/ which stores subtitles in the posts' meta data. In Post Notification emails we want those subtitles to appear below their posts' titles, and so I'm trying to find a hook in MailPoet that would allow me to inject them into the newsletter feed. Because MailPoet is such a large plugin it's been slow going. Have you documented the hooks anywhere? I haven't been able to find anything like that.

**Comment by LordPachelbel** [comment]
I've tried injecting the subtitles into the newsletter posts by hooking into `the_content`, `the_title`, and `the_excerpt`, e.g.:

```
add_filter('the_content', 'inject_subtitles_into_newsletter', 10, 5);
function inject_subtitles_into_newsletter($content) {
	$id = get_the_ID();

	$subtitle = '';
	if ( is_numeric($id) && $id > 0 && function_exists( 'get_the_subtitle' ) ) {
		$subtitle = get_the_subtitle( $id );
		if(!empty($subtitle)) {
		    $subtitle = '<h2 class="subtitle">' . $subtitle . '</h2>';
		}
	}

	return $subtitle . $content;
}
```

None of this stuff shows up in the newsletters, because as far as I can tell from looking at the source coe, MailPoet doesn't seem to be using WP core functions like `get_the_title()`, `get_the_content()`, etc., and so WP core's hooks don't help in this situation.

**Comment by costasovo** [comment]
We do have some filters in our code but they are not intended to be used by the third party and they are not documented.

As for fetching posts, we use WordPress method `getPosts` to fetch posts for a newsletter
and later we use title and content directly from the post object (e.g. fetching post (https://github.com/mailpoet/mailpoet/blob/0573a7915e500524b8d76863d79eb39137feb2c5/lib/Newsletter/Editor/PostTransformer.php#L203-L204)).
We don't use `the_title` and `the_content` filters because of possible rendering issues.

Unfortunately, there is no nice way how you can change post content in a newsletter via a filter. One possible filter you could use is a `mailpoet_sending_newsletter_render_after` which receives 2 arguments: `$rendered_newsletter, $newsletter`.
You can find the HTML of the whole newsletter in `$rendered_newsletter['html']`.

**Comment by aurovrata** [comment]
here is a [list](https://kb.mailpoet.com/article/274-list-of-filters-and-actions) of hooks available, but the documentation is terse and best to look into the code to understand what it does
