### ISSUE TITLE
Update Twig dependency

### ISSUE THREAD

**Issue by eteubert** [mailpoet/mailpoet#1904]
If I see it correctly you are shipping with Twig 1.38.0 and I would like to request an update to 1.38.3 which fixes a few things that are required for [Podlove Publisher plugin](https://github.com/podlove/podlove-publisher/issues/1039). And it looks like your version of Twig gets precendence when loading over the version I include in the plugin so a quick fix would be very much appreciated :)

**Comment by hannesN** [comment]
I checked it, deactivating MailPoet temporarily fixes the Problem with Podlove.

**Comment by pavel-mailpoet** [comment]
Hello, thank you for this issue. This is actually a problem we've been dealing with the last week. We were shipping with 1.36.0 until the last release. This Twig version had some security vulnerabilities. 

We updated Twig to 1.38.0 in the last release but that turned out to be a problem because we started to have conflicts with some plugins. One of them is `Data Tables` by `Supsystic`. 

So we definitely need to investigate this problem more and check the compatibility with other plugins.
