### ISSUE TITLE
MailPoet\Cron\DaemonHttpRunner::pauseExecution is the bad boy

### ISSUE THREAD

**Issue by soderlind** [mailpoet/mailpoet#2574]
New Relic transactions log tags `MailPoet\Cron\DaemonHttpRunner::pauseExecution` as the "bad boy", it's extremely slow,  (first column is duration in milliseconds, second column is duration in percent):

![Transactions - nettsteder regjeringen no - New Relic 2020-01-27 12-12-53](https://user-images.githubusercontent.com/1649452/73170565-0b618500-40ff-11ea-8f37-c688d79ee1cb.png)

**Comment by costasovo** [comment]
Hi @soderlind. Thank you for your report. The observation that a significant amount of time is spent inside `MailPoet\Cron\DaemonHttpRunner::pauseExecution` is caused by the design of HTTP cron runner.
The cron call itself in intervals and when it has nothing to do it pauses (calls sleep();) and wait for the next interval.

In case that this behaviour is inconvenient for you, you can change settings of the plugin to use system cron. Please see [related article in the knowledge base](https://kb.mailpoet.com/article/257-setting-the-server-side-cron-linux-cron).
