### ISSUE TITLE
MailPoet plugin overwrite some MonsterInsights Pro CSS

### ISSUE THREAD

**Issue by JustinyAhin** [mailpoet/mailpoet#2601]
I'm using Mailpoet and MonsterInsights Pro on an installation.

I noticed that when being on all options pages of the plugin, MonsterInsights dashicon is deformed (see attached screenshot).

A small investigation show that there are some CSS rules that disapearred on MailPoet options pages:

`
#toplevel_page_monsterinsights_reports .wp-menu-image img, #toplevel_page_monsterinsights_settings .wp-menu-image img, #toplevel_page_monsterinsights_network .wp-menu-image img {
    width: 18px;
    height: 18px;
    padding-top: 7px;
}
`

I cannot investigate further now, but I think that some CSS rules in MailPoet plugin overwrite the above code.

![Screenshot_2020-02-11 MailPoet - E-mails ‹ Justin Ahinon — WordPress](https://user-images.githubusercontent.com/33403964/74250274-a7d47b80-4cea-11ea-98f2-23ddba7936eb.png)

**Comment by wxa** [comment]
Hello! Thank you for your report!

On its own admin pages MailPoet tries to unload any non-WP CSS/JS to make sure they don't conflict with the plugin functionality. Sometimes this affects things like other plugins' menu icons. We consider this a very minor cosmetic issue because it's isolated to our pages only. 

Whitelisting every such case isn't on our list of priorities at the moment. We may reconsider this and possibly provide a universal way to solve this in the future.

**Comment by wxa** [comment]
By the way, you can fix that for yourself by whitelisting the plugin CSS with a filter:
```php
add_filter('mailpoet_conflict_resolver_whitelist_style', function ($styles) {
  $styles[] = 'google-analytics-premium'; // plugin name to whitelist
  return $styles;
});
```
