### ISSUE TITLE
I got error with Mailpoet

### ISSUE THREAD

**Issue by ramakrishna143007** [mailpoet/mailpoet#2751]
An error of type E_ERROR was caused in line 416 of the file /home/ramakrishna/public_html/monkeydevice.com/wp-content/plugins/mailpoet/vendor-prefixed/symfony/polyfill-mbstring/Mbstring.php. 
Error message: Uncaught Error: Call to undefined function iconv_strpos() in /home/ramakrishna143/public_html/monkeydevice.com/wp-content/plugins/mailpoet/vendor-prefixed/symfony/polyfill-mbstring/Mbstring.php:416

Stack trace:
#0 /home/ramakrishna143/public_html/monkeydevice.com/wp-content/plugins/mailpoet/lib/Util/Polyfills.php(44): MailPoetVendor\Symfony\Polyfill\Mbstring\Mbstring::mb_strpos('Full Specifica...')

#2 /home/ramakrishna143/public_html/monkeydevice.com/wp-content/plugins/easy-table-of-contents/easy-table-of-contents.php(612): Easy_Plugins\Table_Of_Contents\String\mb_find_replace(Array, Array, '

**Comment by flakas** [comment]
Hello @ramakrishna143007,
Thanks for the issue report.

The issue is missing iconv support.
Normally PHP has the iconv extension enabled by default ([PHP docs](https://www.php.net/manual/en/iconv.installation.php)), although it is possible to compile PHP without it.
In order to fix this issue you would need to enable the iconv extension.
Optionally, we are currently working on automatically polyfills in #2749, which should also fix the issue for you.
