### ISSUE TITLE
Import Bug

### ISSUE THREAD

**Issue by carles-estevadeordal** [mailpoet/mailpoet#2825]
**Describe the bug**
TypeError: e.errors is undefinedadmin.a6b95844.chunk.js:42:264563
    dl https://evolutive.co/wp-content/plugins/mailpoet/assets/dist/js/admin.a6b95844.chunk.js:42
    jQuery 7
        i
        fireWith
        then
        i
        fireWith
        x
        c

**To reproduce**
Go on to subscribers, press import, choose file, select a list, click next. And when the script is importing the bug appears.

**Actual behavior**
Cannot import emails, the import feature fails.

**Expected behavior**
It should proceed to the imported emails.

**Versions (please complete the following information):**
- WordPress version: 5.4.1
- PHP version: 7.2.11
- MailPoet version: 3.47.1

**Comment by JanJakes** [comment]
Hi @carles-estevadeordal, I tried this but I was not able to replicate the issue. My guess is this could be caused by a conflict with another plugin.

Could you please reach out to our support team via our [support page](https://www.mailpoet.com/support)? They will be better set up to help debug your particular case.

Thanks!
