### ISSUE TITLE
[Feature] Welcome Emails should be possible during data import

### ISSUE THREAD

**Issue by mokkin** [mailpoet/mailpoet#3163]
Actually we have to import every client manually to our client list to send the welcome mail. The client comes from our CRM-System.
It would be much better to do that with a bulk import. The existing data import tool is absolutely perfect for that, just the option "send welcome mail" to subscribers is missing.

**Comment by NeosinneR** [comment]
Hi @mokkin it's not something we plan to do in foreseeable future, but it's on our radar. Since this is a feature request, I'll close this issue and if you'd like, you can vote for this feature on https://mailpoet.canny.io/feature-requests/p/option-to-send-confirmation-e-mail-for-imported-list-and-auto-triggering-welcome (and if you have any other feature request, feel free to add or vote for the existing one there).
