### ISSUE TITLE
[question] How to segment a mailing on a Custom field ?

### ISSUE THREAD

**Issue by Cyrille37** [mailpoet/mailpoet#3310]
Hello,

I don't understand why we can add custom fields on MailPoet form but cannot use them to segment (filter) a mailing ... So what are they for ?

The use case is to send a mail to an existing MailPoet list filtered (segmented) on a custom field (like the country).

So as a developer I had a look at `MailPoet\Segments\DynamicSegments\FilterHandler::apply()` but it's hard coded with known filters (user_role, email and woocommerce), that I could not find a way to add a filter for MailPoet's custom fields, that I could write...

May I miss something ?
Regards, Cyrille.

**Comment by Cyrille37** [comment]
related/duplicate of #3059

**Comment by Cyrille37** [comment]
I started to code Segment type for Custom field on my branch [segment_on_customfield](https://github.com/Cyrille37/mailpoet/tree/segment_on_customfield). The "select" Custom field works ... Let's continue those days for others custom field "types".

I found how to code & build, but I do not yet know how to manage tests ...

**Comment by NeosinneR** [comment]
Hi @Cyrille37, there are other use-cases for custom fields, but I understand, that segmentation seems like an obvious (and a missing) one. We do plan to add it!

Currently, as you have found out, there isn't a way to segment by MailPoet's custom field. But better segmentation being [the second most requested feature](https://feedback.mailpoet.com/feature-requests?sort=top), we do plan to focus on it in near future. 

And since that will probably require some (maybe significant) code refactor, I can't assure you, that we'll be able to merge your PR (if you decide to make one), because it might collide with the way we plan to implement it (and other new segments). 

I'll close this issue, but if you want to continue discussing it, we can do it here. Optionally, you can upvote [the feature request](https://feedback.mailpoet.com/feature-requests/p/better-segmentation-options), so you'll receive updates once we start working on it.

**Comment by Cyrille37** [comment]
Thanks for that news. I voted ;-)
Regards, Cyrille.
