### ISSUE TITLE
Mailpoet v2.14 Sendgrid API issue

### ISSUE THREAD

**Issue by mapsmarketing** [mailpoet/mailpoet#3352]
**Describe the bug**
The current implementation of Sendgrid API on Mailpoet 2 v2.14 does not allow for sending emails through. It requires some modification to the code to get it going again, more info: https://sendgrid.com/docs/for-developers/sending-email/v2-php-code-example/

**To reproduce**
1. Go into the Mailpoet 2 'Send with' settings
2. Sendgrid enter logins and tick the web API checkbox
3. Hit update

**Actual behavior**
Sendgrid API is rejecting the old authentication method used.

**Expected behavior**
Emails should be sent via Sendgrid API using a generated API key.

**Versions (please complete the following information):**
- WordPress version: 5.5.1
- PHP version: 7.4.2
- MailPoet version: 2.14

**Additional context**
I've modified the `class.sendgrid.php` with the necessary changes shown on the Sendgrid API page mentioned above and it's working again. Please see file attached.

[class.sendgrid.php.zip](https://github.com/mailpoet/mailpoet/files/6032673/class.sendgrid.php.zip)

**Comment by wxa** [comment]
Hi @mapsmarketing,

Due to recent changes done by SendGrid, it seems that when 2FA is enabled, you can't use the SMTP authentication method in MailPoet 2.

You must switch to the API-based one, and this is only available in MailPoet 3.

MailPoet 2 is not supported anymore, and we have no plans to make updates to its sending methods as of now. We recommend everyone having this issue to switch to MailPoet 3.

**Comment by mapsmarketing** [comment]
Hi @wxa ,

The above update (attached file) fixes the issue and it's working just fine, so upgrade to MailPoet 3 is not really necessary.

Unfortunately, not everyone wants to make the move to MailPoet 3 as yet due to a number of reasons some of which is the hassle of migration: https://kb.mailpoet.com/article/199-checklist-after-migrating-to-mailpoet3

All the best.
