### ISSUE TITLE
Paragraph to Heading Transition No Space

### ISSUE THREAD

**Issue by deke207** [mailpoet/mailpoet#3635]
**Describe the bug**
Newsletter, post, full post option appears to be ignoring the space rendered on the post.

**Actual behavior**
Newsletter renders post without spacing between end of paragraph and heading.

**Expected behavior**
Formatting to be the same as the post content.

**Screenshots**
[Droplr](https://d.pr/i/UUjD1Q)

**Versions (please complete the following information):**
- WordPress version: [5.8]
- PHP version: [7.4.21]
- MailPoet version: [3.67.0]

**Additional context**
Post used in the newsletter (screenshot) [Link](https://awesome.blog/2021/08/restaurants-how-to-thrive.html)

**Comment by pavel-mailpoet** [comment]
Thank you @deke207 for the report. We are aware of this problem and we will fix it.

**Comment by deke207** [comment]
@pavel-mailpoet I've received another message from one of our Team 51 partners inquiring about this issue. Any ETA on when this issue we'll be worked on? Thank you.

**Comment by rodrigoprimo** [comment]
Hi, @deke207! Unfortunately, we cannot provide an ETA. Earlier this week, our product manager moved this issue in our internal issue tracking tool for a specification review from one of our developers. This is one of the final stages before someone works on it. So this should get fixed sooner rather than later. We will make sure to update this issue once a fix is released.

**Comment by deke207** [comment]
@rodrigoprimo Sounds good, thank you!

**Comment by pavel-mailpoet** [comment]
Hello @deke207 today we released version 3.71.2 and that contains a fix to the problem.

**Comment by deke207** [comment]
Great news @pavel-mailpoet! Thank you for letting me know. 😄
