### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by Jacks-Eliquid** [mailpoet/mailpoet#4055]
**Describe the bug**
Running Mail Poet on my site and using query monitor it is showing a PHP error see screen shot for details.

**Screenshots**

**Additional context**
![Screenshot 2022-04-06 at 14 08 08](https://user-images.githubusercontent.com/75417993/161982152-24783c9b-7248-4444-90e7-15a0ddd24c08.png)

**Comment by JanJakes** [comment]
Hi @Jacks-Eliquid, thanks for contacting us.

If you believe there is a bug in the plugin and the error you're seeing is not caused by some invalid data or 3rd-party plugins, I'll have to ask you for more details and exact steps to reproduce it, ideally on a clean WordPress install. The above screenshot doesn't say much, unfortunately.

If that's not the case, please note that this Github repository is not used for support questions. Please consider asking on the plugin forums (https://wordpress.org/support/plugin/mailpoet/) where you can get answers from the community and also from the MailPoet support team.

If you are a paying customer, you could also use our contact form: https://www.mailpoet.com/support/.

Thanks!
