### ISSUE TITLE
"Contents of this newsletter are corrupted and may be lost" error when newsletters are created without completing the setup flow

### ISSUE THREAD

**Issue by ecgan** [mailpoet/mailpoet#4203]
**Describe the bug**

If I click on the Newsletter "Create" button and then quit the setup flow immediately without selecting a template, and then try to edit the create newsletter email, I will see a `"Contents of this newsletter are corrupted and may be lost, you may need to add new content to this newsletter, or create a new one. If possible, please contact us and report this issue."` error at the top of the page, and also `"Poet, please add prose to your masterpiece before you send it to your followers."` message at the top right and bottom right of the page.

📹 Demo video with my voice (sorry for the low quality, it's due to the 10MB upload limit):

https://user-images.githubusercontent.com/417342/174647029-c67cb763-d646-4226-bc1e-718ca3777262.mov

**To reproduce**

1. Go to new email page: /wp-admin/admin.php?page=mailpoet-newsletters#/new
2. Click on "Create" button in the Newsletter card.
3. You should see the template page. Do not select a template. Instead, go to the email listings page: /wp-admin/admin.php?page=mailpoet-newsletters#/standard
4. Click on the newly created email.
5. You should see the email edit page with the error messages. 

**Actual behavior**

You should see the email edit page with the error messages. 

**Expected behavior**

There shouldn't be error messages. 

**Versions (please complete the following information):**

- WordPress version: 6.0
- PHP version: 7.3.29
- MailPoet version: 3.89.3

**Additional context**

I found this issue when I was doing a research on MailPoet, see pe2C5g-87-p2.

**Comment by NeosinneR** [comment]
Thanks for filling the issue, @ecgan. This is something we are aware of, but I understand that it's not a good UX if you don't finish the template selection step. The same error message is also shown when the email content is malformed (be it invalid JSON or completely missing because of some database issue), so we'd still prefer to show _some_ error message.

Unfortunately, with https://wp.me/pcD9cT-Zw in mind, I don't think this would receive priority anytime soon. But please, let me know if it's a blocker and we can discuss next steps.

**Comment by ecgan** [comment]
@NeosinneR , thanks for the info! I filed the issue because I wasn't sure if you all are aware of it, I searched the issues list and I didn't see related issue on it (and I just recalled you all use JIRA, not GitHub issue). It is not a blocker, so no worry about it. 😄
