### ISSUE TITLE
Translation doesn't work in various places

### ISSUE THREAD

**Issue by NekoJonez** [mailpoet/mailpoet#4441]
I translated as GTE Mailpoet on translate.wp.org to 100% for nl_BE and I notice that a lot of things don't get translated. 

Like, the welcome wizard or the following examples:

![image](https://user-images.githubusercontent.com/4569581/196912208-6f080ec9-1ad0-421b-98f9-4c1f247027a6.png)

![image](https://user-images.githubusercontent.com/4569581/196912340-fe822bfa-6ecf-44e7-b7ee-96fe53cf4137.png)

I don't find those in the .pot file either. So, what's going on here?

**Comment by pavel-mailpoet** [comment]
Hello @NekoJonez,

thank you for your contribution and for translating our plugin. 

I have some bad news. We are using two sources for translations: 

We primarily take our translations from [Transifex](https://explore.transifex.com/wysija/mp3/). 

If we find translations there, we take them from translate.wordpress.org. This is the case for nl_BE. The translation is not on Transifex so we download it from wp.org as a fallback. However, we are using a templating system and the [translations from it](https://github.com/mailpoet/mailpoet/blob/2f823f560605cb569f6f75953140fba21deced2c/mailpoet/views/newsletters.html#L212) are not picked up by WordPress. So even if it seems that you translated 100% of the plugin there is still a lot of it which is not translated because WordPress doesn't know about that. 

Best Regards
  Pavel

**Comment by NekoJonez** [comment]
@pavel-mailpoet I'm willing to do the translation over at Transifex if the nl_BE locale is activated there.
