### ISSUE TITLE
Different MySQL Port not working

### ISSUE THREAD

**Issue by RokkuCode** [mailpoet/mailpoet#5536]
**Describe the bug**
I use a database server listening not on the default port 3306 but on 33080. Mailpoet does not work and reports an error, that it cannot connect the database. This problem exists earlier under the issue #[3468](https://github.com/mailpoet/mailpoet/issues/3468)

The DB_HOST constant is correctly set to '127.0.0.1:33080'

Tested with Wordpress 6.5 and Mailpoet 4.48.1

**To reproduce**

1. Prepare a database server with a different default port (e.g. 33080)
2. Install Mailpoet
3. Get the error message, that the database cannot connected.

**Actual behavior**
Mailpoet is not able to connect to database servers on different ports than the default port.

**Expected behavior**
Mailpoet should be able to connect to database servers on different port than the default port and thus handle the configured DB_HOST data from wordpress correctly.

**Screenshots**
*not available*

**Versions (please complete the following information):**

- WordPress version: [e.g: 6.5]
- PHP version: [e.g: 8.1.27]
- MailPoet version: [e.g: 4.48.1]

**Additional context**

**Comment by brezocordero** [comment]
Hi @RokkuCode 

Thank you for the report.

Issue https://github.com/mailpoet/mailpoet/issues/3468 was fixed and you should be able to use MailPoet with a non default port since then. I checked if there had been any changes in the code that could have caused a regression but there was nothing obvious. Maybe your issue is specific to your setup or we need more information.

I set up a site using the following and I could not reproduce your problem:
- MySQL Database server listening on 33080
- wp-config.php with DB_HOST 127.0.0.1:33080
- WordPress version: [e.g: 6.5]
- PHP version: 8.1.13
- MailPoet version: 4.48.1

Could you please give us more information to see if we can reproduce it?
- When did the problem start happening?
- Could you give us more details of your setup?

Thanks.
